### ISSUE TITLE
CJ Feature: Color picker styling

### ISSUE THREAD

**Issue by KateMcRo** [KateMcRo/creativeJuice#77]
**Color Picker**
- [x] In it's own div/modal
- [x] "Choose a starting point for your color palette:"
- [x] Colors arranged in 4 rows of 6
- [x] Spaced/styled consistently with page
- [x] Looks similar to the attached image

<img width="335" alt="Classic Rainbow" src="https://user-images.githubusercontent.com/113201586/226981185-2d33ef45-9cb1-4a2d-86f8-edbd5df1d0ed.png">

**Comment by KateMcRo** [comment]
If time becomes an issue, I can style this on the JS side. Just let me know what you'd like to do.

**Comment by DanielFMcKay** [comment]
3 x 8 seems to be more practical for visual alignment, as it turns out
