### ISSUE TITLE
CJ Ticket Grooming

### ISSUE THREAD

**Issue by KateMcRo** [KateMcRo/creativeJuice#80]
**Missing**

- [x] Start button reveals word modal (previously hidden)
- [x] Word modal has input to call API 
- [x] Word API populates tiles
- [x] On Word API submit, it is replaced with Color Modal
- [x] Color modal prompts user to select color
- [x] On Color Modal click, it is replaced with Results Modal

_Results Modal_

- [x] Has button for retry word that runs synonym function
- [x] Has button for retry color that displays Color Modal again
- [x] Has button for start over that hides all modals
- [x] Results are displayed on full page
- [x] Tiles are staggered and alternate between word/color
- [x] Word tiles are 1/3 height
- [x] Color tiles are 2/3 height

**Comment by DanielFMcKay** [comment]
results modal sub-issues 7 & 8 are ready to be pushed
